# flutter pub get
# flutter pub upgrade -major-versions # 更新Flutter项目的依赖包到major版本
# flutter pub outdated
# open pub.dev

# dart pub global activate flutter_unused_packages # 安装 flutter_unused_packages
# flutter_unused_packages --init # 在项目根目录下初始化配置（可选）📃analize_unused_packages.json
# flutter_unused_packages --analyze # 分析项目中未使用的依赖
# flutter_unused_packages --fix # 自动清理被判定为未使用的依赖

name: jobs_flutter_base_config
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"
# 在dependencies部分中已经声明了某个包，就不需要在dev_dependencies部分重复声明了。
dependencies:
  # 核心库
  flutter:
    sdk: flutter
  jobs_refresh_load:
    path: ./JobsByPubs/JobsRefreshByPub
  jobs_runners:
    path: ./JobsByPubs/JobsRunnersByPub
  jobs_safety_get_value:
    path: ./JobsByPubs/JobsSafetyGetValueByPub
  # UI组件库
  # ym_flutter_widget: any
  flutter_svg: any
  oktoast: any # 轻量级toast
  extended_tabs: any # 扩展TabBar
  cupertino_icons: any
  device_preview: any # 多设备模拟器（外部包裹）
  easy_localization: any # 国际化根容器（外部包裹）
  flutter_phoenix: any # 热重启容器（外部包裹）
  screenshot: any # 截屏操作
  vibration: any # 震动
  carousel_slider: any # 用于轮播图
  card_swiper: any # 用于轮播图
  easy_refresh: any # 用于下拉刷新
  webview_flutter: any # 用于显示网页
  camera: any # 用于拍照
  image_picker: any # image_picker 插件只能分别调用拍照或录像功能，但不能直接调用系统相机应用的完整界面
  flutter_inappwebview: any # 用于显示网页 (iOS)
  flutter_fortune_wheel: any # 用于显示抽奖转盘
  flutter_easyloading: any #
  # google_mobile_ads: any # 用于显示广告。初始化的时候必须要带 Key 否则程序崩溃
  cached_network_image: any # 用于显示网络图片
  # 图片处理
  # flutter_native_image: any # 用于处理原生图片 🚨 打包失败
  flutter_cache_manager: any # 用于处理网络图片(独立缓存控制)
  # 数据处理
  equatable: any # 用于定义值对象的相等性
  built_value: any # 用于序列化/反序列化数据
  built_collection: any # 用于序列化/反序列化数据
  shared_preferences: any # 用于存储键值对数据
  encrypt: any # 用于加密数据
  pointycastle: any # 用于加密数据
  # video_compress: any # 用于处理视频
  json_annotation: any # 用于处理json数据
  # 状态管理
  get: any # 用于管理应用状态
  provider: any # 用于管理应用状态
  flutter_riverpod: any # 用于管理应用状态
  bloc: any # 用于管理应用状态
  flutter_bloc: any # 用于管理应用状态
  # 用户权限处理
  # 网络请求
  dart_ping_ios: any #
  http: any # 用于网络请求
  # Chopper: any # 用于网络请求
  # FlutterHttpClient: any # 用于网络请求
  dio: any # 用于网络请求
  mqtt_client: any # 用于连接MQTT服务器
  # flutter_cache_manager_firebase: any # 用于缓存网络请求 (Firebase)
  # 本地存储
  # get_storage: any # 用于存储键值对数据
  # shared_preferences_web: any # 用于存储键值对数据 (web)
  # shared_preferences_platform_interface: any # 用于存储键值对数据 (platform interface)
  # flutter_secure_storage: any # 用于存储敏感数据
  # flutter_secure_storage_macos: any # 用于存储敏感数据 (macOS)
  sqflite: any # 用于本地数据库
  # 播放器
  video_player: any # 用于播放视频
  audioplayers: ^5.2.1 # 用于播放音频
  # 国际化
  intl: any # 提供国际化和本地化设施，包括消息翻译、复数和性别、日期/数字格式和解析以及双向文本
  # 设备/应用相关
  timezone: any # 用于获取设备时区
  # platform_device_id: any # 用于获取设备唯一标识符 🚨用了device_info打包失败
  # 分享功能
  # 账号登陆
  # 键盘相关
  # 地图相关
  flutter_localizations: # 一个使用地图数据进行应用内定位的软件包
    sdk: flutter
  # 工具库
  wakelock_plus: any # 用于保持屏幕常亮
  flutter_plugin_engagelab: any # 极光推送
  file_picker: any # 实现文件选择器功能，允许用户从本地文件系统中选择任意文件（如图片、PDF、文档、视频等），并获取路径用于上传等操作。
  connectivity_plus: any # 用于检查设备网络连接状态
  url_launcher: any # 用于在移动应用中打开 URLs，包括网页、电子邮件、电话等
  path: any # 用于处理文件路径
  path_provider: any # 用于获取文件路径
  # google_fonts: any # 用于使用Google Fonts字体
  flutter_local_notifications: any # 用于显示本地通知
  auto_route: any # 用于管理应用路由
  flutter_screenutil: any # 用于屏幕适配
  # 应用程序
  # 日志调试
  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any # Flutter代码规范
  build_runner: any
  json_serializable: any
  built_value_generator: any # 用于生成序列化/反序列化代码
flutter_gen:
  output: lib/gen/ # 生成文件的目录
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true # 指示应用程序是否应该使用 Material Design 风格
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets: # 路径名不能有中文，否则可能无法正常读取
    - assets/
    - assets/Fonts/
    - assets/HTML/
    - assets/i18n/
    - assets/Images/
    - assets/Jsons/
    - assets/Lottie/
    - assets/Others/
    - assets/README/
    - assets/SVG/
    - assets/Sounds/
    - assets/Video/
    - lib/resource/

# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
#
# https://fonts.google.com/
fonts:
  - family: Akrobat-Bold
    fonts:
      - asset: assets/fonts/Akrobat-Bold.otf
  - family: Proximanova-bold
    fonts:
      - asset: assets/fonts/ProximaNovaBold.otf
  - family: Schyler
    fonts:
      - asset: assets/fonts/Schyler-Regular.ttf
      - asset: assets/fonts/Schyler-Italic.ttf
        style: italic
  - family: Trajan Pro
    fonts:
      - asset: assets/fonts/TrajanPro.ttf
      - asset: assets/fonts/TrajanPro_Bold.ttf
        weight: 700
